module Tarefa5_2022li1g016_Spec where

import LI12223
import Tarefa5_2022li1g016
import Tarefa2_2022li1g016
import Test.HUnit

jogoT= Jogo (Jogador (5,6)) mapaT

mapaT = (Mapa 11 [(Relva, [Nenhum, Arvore, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Arvore, Arvore]),
                 (Rio (-1), [Tronco, Nenhum, Tronco, Tronco, Tronco, Tronco, Nenhum, Tronco, Nenhum, Tronco, Nenhum]),
                 (Rio 2, [Tronco, Tronco, Nenhum, Tronco, Nenhum, Tronco, Tronco, Nenhum, Tronco, Tronco, Nenhum]),
                 (Rio (-1), [Nenhum, Nenhum, Tronco, Tronco, Nenhum, Tronco, Nenhum, Tronco, Tronco, Nenhum, Tronco]),
                 (Rio 1, [Tronco, Nenhum, Tronco, Nenhum, Tronco, Tronco, Nenhum, Tronco, Tronco, Tronco, Nenhum]),
                 (Estrada 1, [Carro, Carro, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Carro]),
                 (Relva, [Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Arvore, Arvore, Arvore]),
                 (Relva, [Arvore, Nenhum, Nenhum, Nenhum, Nenhum, Nenhum, Arvore, Arvore, Arvore, Arvore, Arvore]),
                 (Relva, [Arvore, Arvore, Nenhum, Nenhum, Nenhum, Arvore, Arvore, Arvore, Arvore, Arvore, Arvore])])

testsT1 :: Test
testsT1 = TestLabel "Testa se a função cria uma linha pseudo-aleatória1" $ test ["Teste 1" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Estrada (-2),[Nenhum,Carro,Carro,Nenhum,Nenhum,Carro,Carro,Carro,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 1]

testsT2 :: Test
testsT2 = TestLabel "Testa se a função cria uma linha pseudo-aleatória2" $ test ["Teste 2" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Relva,[Nenhum,Arvore,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore,Nenhum,Arvore,Arvore]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 2]

testsT3 :: Test
testsT3 = TestLabel "Testa se a função cria uma linha pseudo-aleatória3" $ test ["Teste 3" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Rio (-1),[Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 3]

testsT4 :: Test
testsT4 = TestLabel "Testa se a função cria uma linha pseudo-aleatória4" $ test ["Teste 4" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Estrada (-2),[Nenhum,Carro,Nenhum,Carro,Carro,Carro,Nenhum,Carro,Carro,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 4]

testsT5 :: Test
testsT5 = TestLabel "Testa se a função cria uma linha pseudo-aleatória5" $ test ["Teste 5" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Relva,[Nenhum,Nenhum,Arvore,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 5]

testsT6 :: Test
testsT6 = TestLabel "Testa se a função cria uma linha pseudo-aleatória6" $ test ["Teste 6" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Relva,[Nenhum,Arvore,Arvore,Nenhum,Arvore,Nenhum,Arvore,Nenhum,Arvore,Nenhum,Arvore]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])])~=? deslizaJogo jogoT 17]

testsT7 :: Test
testsT7 = TestLabel "Testa se a função cria uma linha pseudo-aleatória7" $ test ["Teste 7" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 74]

testsT8 :: Test
testsT8 = TestLabel "Testa se a função cria uma linha pseudo-aleatória8" $ test ["Teste 8" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Estrada 2,[Nenhum,Carro,Carro,Nenhum,Carro,Carro,Carro,Nenhum,Nenhum,Carro,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 64]

testsT9 :: Test
testsT9 = TestLabel "Testa se a função cria uma linha pseudo-aleatória9" $ test ["Teste 9" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Estrada 2,[Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 100]

testsT10 :: Test
testsT10 = TestLabel "Testa se a função cria uma linha pseudo-aleatória10" $ test ["Teste 10" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])])~=? deslizaJogo jogoT 92]

testsT11 :: Test
testsT11 = TestLabel "Testa se a função cria uma linha pseudo-aleatória11" $ test ["Teste 11" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Rio 1,[Nenhum,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 57]

testsT12 :: Test
testsT12 = TestLabel "Testa se a função cria uma linha pseudo-aleatória12" $ test ["Teste 12" ~: Jogo (Jogador (5,7)) (Mapa 11 [(Relva,[Nenhum,Arvore,Arvore,Nenhum,Arvore,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Rio (-1),[Tronco,Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco,Tronco,Nenhum]),(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore])]) ~=? deslizaJogo jogoT 35]

testesTarefa5 = (TestList [testsT1, testsT2, testsT3, testsT4, testsT5, testsT6, testsT7, testsT8, testsT9, testsT10, testsT11, testsT11, testsT12])